language: node_js
node_js:
  - 8
  - 10
cache:
  yarn: true
  directories:
    - .npm
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
install: true
script: task/test.sh