const TYPE: ICO = {
  eq: 'eq',
  gt: 'gt',
  gte: 'gte',
  lt: 'lt',
  lte: 'lte',
  and: 'and',
  divide: 'divide',
  multiply: 'multiply',
  add: 'add',
  minus: 'minus',
  max: 'max',
  min: 'min',
  avg: 'avg',
  desc: 'desc',
  asc: 'asc',
  count: 'count',
  toUInt32: 'toUInt32',
  interval: 'interval',
  toUnixTimestamp: 'toUnixTimestamp',
  toDateTime: 'toDateTime',
  toStartOfInterval: 'toStartOfInterval',
  splitArray: 'splitArray',
  wrap: 'wrap',
  toString: 'toString',
  rename: 'rename',
  as: 'as',
  in: 'in',
  uniq: 'uniq',
  operate: 'operate',
};

export default TYPE;
